### PR TITLE
ORCA-557: Enable Domo

### PR DESCRIPTION
**Pull request by secretsayan**
**Motivation**
This adds Google API related credentials to enable Domo Integration.

### CODE REVIEW

**Comment by secretsayan** [comment]
@vishalkhode1 Please review

**Comment by vishalkhode1** [comment]
@secretsayan Changes looks good to me. I believe we need to add secret variables as well in Github CI. Right ?

**Comment by secretsayan** [comment]
> @secretsayan Changes looks good to me. I believe we need to add secret variables as well in Github CI. Right ?

That has already been done. If you can check in the settings tab you would already find it there.

**Comment by vishalkhode1** [comment]
@secretsayan Thanks, I can see those variables. We need this for 1.x branch as well ?
> > @secretsayan Changes looks good to me. I believe we need to add secret variables as well in Github CI. Right ?
> 
> That has already been done. If you can check in the `settings->"secrets and variables"->actions` tab you would already find it there.

**Comment by secretsayan** [comment]
Currently, ORCA does not send branch specific test results to Domo so we are doing this activity on the primary branch only. But surely, the other branches will also be included in some time. We will notify you once we start that activity.

**Pull request merged**
