### PR TITLE
Add test scaffolding for Code Studio.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
Example output from `composer test`:
image

**Comment by grasmash** [comment]
Failing due to unrelated patch failure.

**Comment by grasmash** [comment]
Depends on https://github.com/acquia/cli/pull/755

**Review by danepowell — APPROVED** [review]
Looks good. We need to wait for a new ORCA release and rebase on master before merging, tests are quite unstable at the moment.

**Comment by grasmash** [comment]
But they're passing!

**Comment by danepowell** [comment]
> But they're passing!

What a lovely world you must live in, where tests passing now keep passing after you merge 😄 

ORCA's cutting a new release now, this will be resolved momentarily...

**Pull request merged**
